import {
  pgTable,
  integer,
  serial,
  text,
  boolean,
  timestamp,
  unique,
} from "drizzle-orm/pg-core";

export const bills = pgTable("bills", {
  billId: integer("bill_id").primaryKey(),
  billNumber: text("bill_number"),
  title: text("title"),
  status: text("status"),
  chamber: text("chamber"),
  changeHash: text("change_hash"),
  lastAction: text("last_action"),
  lastActionDate: text("last_action_date"),
  url: text("url"),
  // Plain-language source text used as input to the AI analysis (LegiScan synopsis).
  billText: text("bill_text"),
  // FEATURE — AI-powered analysis (generated by scripts/summarize.ts).
  aiSummary: text("ai_summary"),
  aiProArguments: text("ai_pro_arguments"),
  aiConArguments: text("ai_con_arguments"),
  createdAt: timestamp("created_at").defaultNow(),
});

export const legislators = pgTable("legislators", {
  peopleId: integer("people_id").primaryKey(),
  name: text("name"),
  party: text("party"),
  role: text("role"),
  district: text("district"),
  imageUrl: text("image_url"),
  // 2026 reelection status. null = unknown, true = confirmed running in the
  // November 2026 election, false = not running / retiring.
  runningForReelection: boolean("running_for_reelection"),
  createdAt: timestamp("created_at").defaultNow(),
});

export const billSponsors = pgTable(
  "bill_sponsors",
  {
    id: serial("id").primaryKey(),
    billId: integer("bill_id").references(() => bills.billId),
    peopleId: integer("people_id").references(() => legislators.peopleId),
    name: text("name"),
    party: text("party"),
    isPrimary: boolean("is_primary").default(false),
    createdAt: timestamp("created_at").defaultNow(),
  },
  // A person sponsors a given bill at most once. Prevents the duplicate-row
  // accumulation that the dedupe-sponsors script cleaned up; the ingestion
  // inserts use onConflictDoNothing against this.
  (t) => ({
    billPeopleUnique: unique("bill_sponsors_bill_people_unique").on(
      t.billId,
      t.peopleId
    ),
  })
);

export const votes = pgTable("votes", {
  rollCallId: integer("roll_call_id").primaryKey(),
  billId: integer("bill_id").references(() => bills.billId),
  date: text("date"),
  // What this roll call was on, from LegiScan ("Amendment 3", "Second Reading",
  // "Veto Override", "M11 Concur", etc.). `desc` is a SQL reserved word, so the
  // column is named vote_desc; the JS field is `description`.
  description: text("vote_desc"),
  chamber: text("chamber"),
  yea: integer("yea"),
  nay: integer("nay"),
  nv: integer("nv"),
  absent: integer("absent"),
  passed: boolean("passed"),
});

export const voteDetail = pgTable("vote_detail", {
  id: serial("id").primaryKey(),
  rollCallId: integer("roll_call_id").references(() => votes.rollCallId),
  peopleId: integer("people_id").references(() => legislators.peopleId),
  name: text("name"),
  party: text("party"),
  vote: text("vote"),
});
